version: "3.9"

services:
  cv-matcher:
    build: .
    container_name: cv-ranker
    depends_on:
      - qdrant
    ports:
      - "8050:8050"  
    environment:
      PYTHONUNBUFFERED: 1
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
    command: >
      python app.py  # Use the python command to run the Dash app
    restart: always
    networks:
      - cvnet

  qdrant:
    image: qdrant/qdrant:v1.12.4
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__STORAGE__STORAGE_PATH: /qdrant/storage
    networks:
      - cvnet

volumes:
  qdrant_data:

networks:
  cvnet:
    driver: bridge